[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable HTTP/2 and HTTP/3 for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Enable better caching of assets
    Cache-Control = "public, max-age=31536000, immutable"

# Specific caching for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Optimize JavaScript assets
[[headers]]
  for = "/_next/static/chunks/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize CSS assets
[[headers]]
  for = "/_next/static/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize image assets
[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize font files
[[headers]]
  for = "/_next/static/media/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set prioritization for critical resources
[[edge_functions]]
  function = "early-hints"
  path = "/*"